### ISSUE TITLE
Is it possible to process in chunks?

### ISSUE THREAD

**Issue by TrevorHinesley** [bbc/audiowaveform#100]
I'm working on something with extremely large files, the largest being anywhere from 2GB to 8GB. I'd like to run audiowaveform in AWS Lambda, but the maximum memory available is 3GB. Is it possible to only process a file in chunks somehow, then piece together the dat file?

**Comment by chrisn** [comment]
What's the use case for the dat files you're creating? If you're planning to use them in a web application, e.g., with Peaks.js, then you'll have memory issues in the browser loading a 3GB dat file, so splitting the audio into chunks before processing with audiowaveform may be preferable.

audiowaveform currently stores the entire generated dat file in memory before writing it to file. It's possible we could change this to write the output in chunks, which would save memory during processing.

**Comment by TrevorHinesley** [comment]
That would be incredible if it was possible to split it into chunks (if I'm understanding you correctly), not only for being able to run audiowaveform on file chunks (rather than the entire X GB file), but especially since it could then be possible to use the multiple separate .dat files on the front-end to piece together needed content (i.e. draw the waveform in sections) without needing one huge .dat file in browser memory.

**Comment by chrisn** [comment]
I'd like to clarify what's needed, as I think we're talking about two distinct things:
* One is memory usage running audiowaveform on large audio files in AWS Lambda. Are you getting out of memory errors in practice?
* The other is producing .dat files that can be consumed by a web front end. A solution here could be to use a single large .dat file and make byte range requests to access chunks.

**Comment by TrevorHinesley** [comment]
@chrisn the main issue I'm referring to is your first point, memory usage in Lambda. I haven't started working on this piece, because of Lambda's memory drawbacks. The maximum RAM in Lambda is 3GB. Does audiowaveform load the entire file into memory while processing? If not, how does it do it? I can run some tests to see when it starts to give out if it processes the file line by line, unless it loads the whole file into memory, in which case Lambda functions using audiowaveform would basically just be limited to 2.5-3GB files.

For the second point, you're correct that shouldn't be too big of an issue.

**Comment by chrisn** [comment]
audiowaveform doesn't load the entire audio file into memory while processing, but it does store the entire generated waveform data before saving it out as a .dat file, so memory usage would depend on the zoom level (`-z`) setting you use.

**Comment by TrevorHinesley** [comment]
Got it. I'll just put it into practice and see what the real-world implications of this look like! Thanks a ton.

**Comment by TrevorHinesley** [comment]
Actually, looks like Lambda only offers 500MB of temp storage per function execution, so being able to split a file into chunks, then allowing audiowaveform to process each chunk sequentially, and finally putting the concatenated .dat or .json file together at the end, would be the route to go.

**Comment by chrisn** [comment]
You can use ffmpeg to split the audio into chunks, and it would be fairly straightforward to write a tool that would concatenate the .json or .dat formats at the end.

**Comment by TrevorHinesley** [comment]
Good idea. I'll report back on the success of this after I dive in over the next couple weeks!

**Comment by TrevorHinesley** [comment]
After processing a 6GB file in chunks (I believe I did 400MB chunks), and piecing together the audiowaveform results of each chunk, it worked, but came out to be one peak longer than doing the whole 6GB file raw (and the peaks were different than just processing the whole file at one time, which I'm sure is related to how averaging ranges of peaks to arrive at the defined pixels-per-second would differ once the file is split into sections). I'm not yet sure if this has something to do with how FFMPEG splits files using trim and offset, or if it's related to how audiowaveform is calculating pixels-per-second for the chunks. Will report back after more digging.

**Comment by Joshfindit** [comment]
Be very wary of splitting audio in to chunks. I did some rigorous testing and found that common tools were dropping or misaligning frames when working on large numbers of splits.

I had to have someone make this file in matlab so that it was a perfect measuring stick for splits (I was/am doing all audio in to 7-second segments for a personal project):

https://archive.org/details/72MinuteAudioFileWithTonesAt7SecondIntervals
(Created to be public domain)

**Comment by TrevorHinesley** [comment]
@Joshfindit thank you for sharing that! Should I be concerned if the chunks are just being used to generate waveforms? The original file is in tact for playback, I'm just chunking it for processing the waveform data to save a .dat or .json file from. If so, is there a reliable way to chunk that you've found?

**Comment by TrevorHinesley** [comment]
According to this, `-ss` is frame accurate: https://superuser.com/a/459488 -- did that not work for you?

**Comment by Joshfindit** [comment]
> @Joshfindit thank you for sharing that! Should I be concerned if the chunks are just being used to generate waveforms? The original file is in tact for playback, I'm just chunking it for processing the waveform data to save a .dat or .json file from. If so, is there a reliable way to chunk that you've found?

I have my notes somewhere, not sure where at the moment. I did find *one* of the audio-splitting tools was accurate.
However, if you’re just chunking for a visual reference I don’t imagine a couple dropped frames or a drift of a few seconds is going to hurt.
