### ISSUE TITLE
Uppercase file extensions

### ISSUE THREAD

**Issue by jfdsr** [bbc/audiowaveform#110]
I have an issue when running audiowaveform that if the file extension is uppercase (for example for input file "test.WAV") then this does not generate the waveform data as it fails.
Is this an enhancement that can be done to the mapping in FileFormat.cpp?

**Comment by chrisn** [comment]
Can you provide an example command line that isn't working?

This works OK for me: `audiowaveform -i testfile.WAV -o testfile.DAT -b 8`

**Comment by jfdsr** [comment]
Cheers works on latest version, it was due to previous version being installed and also noting the change of writing status messages to stderr instead of stdout was throwing an issue for me. Thanks for adding to test cases too. :)
