### ISSUE TITLE
Feature: support for ARM64 systems

### ISSUE THREAD

**Issue by radioguy0** [bbc/audiowaveform#116]
I recently found that this software is incorporated in another project’s application which I am running on an ARM64 device. I recently discovered that the software doesn’t have a tailored build to accommodate this type of system. Is this something that you plan to incorporate in future versions?

**Comment by chrisn** [comment]
This sounds like a good idea. I haven't tried building for ARM, I expect the code will need changing to fix the binary waveform data (.dat) format output due to differences in endianness. Are you able to help with getting it to compile? Which OS are you targeting?

**Comment by radioguy0** [comment]
@chrisn The plan would be to be able to use it in a system that runs on Ubuntu 18.04 through an ARM64 device for now. Not familiar with the process involved of compiling versions for other systems nor would I be a regular programmer, more of an enthusiast who would like to learn and offer help if it’s not beyond my capabilities. Any advice / suggestions for learning are welcome of course. Would be great to connect offline to discuss in more depth, if that would be something you would be interested in?

**Comment by chrisn** [comment]
I have just published packages for ARM Ubuntu. You can install from my PPA using the instructions [here](https://github.com/bbc/audiowaveform#ubuntu).
