### ISSUE TITLE
Install Error: Could NOT find LibGD (missing: LIBGD_LIBRARIES LIBGD_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by 1c7** [bbc/audiowaveform#117]
## Enviroment
* Operating System: macOS Catalina 10.15.5 (Macbook Pro 2017 15 inch)

## Expected behavior
`cmake ..` work fine without any error

![image](https://user-images.githubusercontent.com/1804755/83332293-ec514a80-a2cc-11ea-826e-e7a755113f01.png)

## What actually happen
when I run 
```
cmake -D CMAKE_C_COMPILER="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc" -D CMAKE_CXX_COMPILER="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++" ..
```
within `build/` empty folder

Ouput these error message:
```
-- Build type not specified: default is Release
-- CMAKE_VERSION=3.17.3
-- Build type: Release
-- CMAKE_MODULE_PATH='/Users/remote_edit/Documents/TimelineSoftware/audiowaveform/cmake/modules'
-- Building version 1.4.2
CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find LibGD (missing: LIBGD_LIBRARIES LIBGD_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibGD.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:84 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/remote_edit/Documents/TimelineSoftware/audiowaveform/build/CMakeFiles/CMakeOutput.log".
See also "/Users/remote_edit/Documents/TimelineSoftware/audiowaveform/build/CMakeFiles/CMakeError.log".
```

## The main error message is 
```
Could NOT find LibGD (missing: LIBGD_LIBRARIES LIBGD_INCLUDE_DIRS)
```

I tried to Google and solve this myself but haven't found any solutions that works

## Question: How to solve this `cmake` error when I try to build from source?
Thank you!

**Comment by 1c7** [comment]
I am not sure If I provide all the necessary info for debugging
If you need to know more about enviroment in order to debug, let me know :smile:

**Comment by chrisn** [comment]
Have you installed libgd?

Alternatively, have you tried installing using [Homebrew](https://github.com/bbc/audiowaveform#mac-osx-via-homebrew) to install audiowaveform?

**Comment by 1c7** [comment]
@chrisn  Thanks for reply!

## Problem Solved!
```
brew install libgd
```
> Warning: gd 2.3.0 is already installed, it's just not linked
> You can use `brew link gd` to link this version.

```
brew link gd
```
> Linking /usr/local/Cellar/gd/2.3.0...
Error: Could not symlink bin/annotate
Target /usr/local/bin/annotate
already exists. You may want to remove it:
  rm '/usr/local/bin/annotate'

> To force the link and overwrite all conflicting files:
  brew link --overwrite gd

> To list all files that would be deleted:
  brew link --overwrite --dry-run gd

```
brew link --overwrite gd
```

> Linking /usr/local/Cellar/gd/2.3.0... 29 symlinks created

```
brew install audiowaveform
```

```
audiowaveform -v
```
> AudioWaveform v1.4.2
