### ISSUE TITLE
Unable to locate package audiowaveform

### ISSUE THREAD

**Issue by SwissCheese5** [bbc/audiowaveform#119]
```
> sudo apt-get install audiowaveform

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package audiowaveform
```

Result from sudo apt-get update:
```
W: The repository 'http://ppa.launchpad.net/chris-needham/ppa/ubuntu groovy Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/chris-needham/ppa/ubuntu/dists/groovy/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by chrisn** [comment]
I'm unlikely to release packages for Ubuntu 20.10 (groovy) before it's official release date. For now, you'll need to build from source.

**Comment by SwissCheese5** [comment]
but I'm using Google cloud run, no way around this? I've never built from source before.

**Comment by chrisn** [comment]
I recommend using an LTS Ubuntu release.

My reasoning is that we had problems last time I released early (see https://github.com/bbc/audiowaveform/issues/113)

**Comment by SwissCheese5** [comment]
@chrisn Can debian8 work? I'm very limited on options

**Comment by chrisn** [comment]
You'll have to compile from source to run on Debian 8. Are you creating a Docker image? If so, you should be able to select the Linux distro and version.

**Comment by SwissCheese5** [comment]
Ended up with using
`FROM ubuntu:18.04`
:)
