### ISSUE TITLE
Max channels == 8?

### ISSUE THREAD

**Issue by TrevorHinesley** [bbc/audiowaveform#120]
[This line](https://github.com/bbc/audiowaveform/blob/9d50094ef069ac808b5865c02b94c2fed0f4398e/src/WaveformGenerator.cpp#L140) limits the max number of channels to 8. Is there any technical reason for that? Hitting this limit with a 10-channel audio file.

**Comment by chrisn** [comment]
I think this is arbitrary, we could change it, or even remove it I guess.

**Comment by chrisn** [comment]
I increased the max number of channels to 24 in the v1.5.0 release.
