### ISSUE TITLE
build fails on ubuntu bionic

### ISSUE THREAD

**Issue by Br3nda** [bbc/audiowaveform#123]
```[ 64%] Linking CXX executable audiowaveform_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libvorbis.a(psy.o): in function `setup_tone_curves':
(.text+0x11e2): undefined reference to `__log_finite'
```
Is there an extra dependency i need to install??

Full output:
https://gist.github.com/Br3nda/66d9b3ad0b1032909353ebce0e920267

**Comment by chrisn** [comment]
The functions `__log_finite` etc come from libm.

I have successfully compiled audiowaveform using Ubuntu 18.04 and g++ 9.3.0 using install information [here](https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04) - see [this Dockerfile](https://gist.github.com/chrisn/d0052d55299f9e3b160682f08489445a).

**Comment by Br3nda** [comment]
seems to happen only when building static after a `cmake -D BUILD_STATIC=1 ..`

**Comment by chrisn** [comment]
The Dockerfile example (just updated) works for static builds. Is there some difference between this and your build environment?

**Comment by chrisn** [comment]
I'll close this, but feel free to re-open if you are still having build issues.
