### ISSUE TITLE
Need one liner command for producing multiple audio file and their JSON 

### ISSUE THREAD

**Issue by kinan53** [bbc/audiowaveform#126]
Hi,
am using audiowaveform on windows 10 machine and i need a one liner command to produce multiple audio jsons at a same time..
as i have 3GB of audios and it will take ages to manually convert them one by one...

if anyone can give some kind of command or script from which one can produce multiple JSONs at a single time that would be great !

**Comment by chrisn** [comment]
You could use a batch file, like this:

```bat
REM batch_audiowaveform.bat
for %%F in (*.flac) do audiowaveform -i "%%F" -o "%%~nF.dat" -b 8 -z 128
```

**Comment by kinan53** [comment]
ok... let me try that !
