### ISSUE TITLE
Ogg Opus codec support

### ISSUE THREAD

**Issue by tommedema** [bbc/audiowaveform#127]
The readme specifies which contains are supposed, but what about codecs? E.g. is ogg container with opus codec supported?

**Comment by chrisn** [comment]
Ogg Vorbis is supported, but not (yet) Ogg Opus. This is because libsndfile 1.0.29 - which is needed for Opus support - hasn't made its way into Linux distributions, particularly Ubuntu, yet. One libsndfile is updated, Opus support will be trivial to add to audiowaveform.

**Comment by tommedema** [comment]
Ah, too bad. When it does support Ogg Opus would be great to get an update on this :)

**Comment by jonathanhood** [comment]
It looks like libsndfile 1.0.31 is now available in Ubuntu Jammy. Is it easy to get this support added with that new library in place?

**Comment by chrisn** [comment]
There's an audiowaveform build available for Jammy in my [PPA](https://launchpad.net/~chris-needham/+archive/ubuntu/ppa/+packages), so this should "just work".
