### ISSUE TITLE
How to get mp3 duration use audiowaveform command?

### ISSUE THREAD

**Issue by Yunfei1982** [bbc/audiowaveform#130]
How to get mp3 duration use audiowaveform command?

thanks!

**Comment by chrisn** [comment]
The duration is reported in the output as `Frames decoded`, 7.164 seconds in this example:

```
$ audiowaveform -i test_file_stereo.mp3 -o test.json -b 8
Input file: test_file_stereo.mp3
Format: Audio MPEG layer III stream
Bit rate: 128000 kbit/s
CRC: no
Mode: normal LR stereo
Emphasis: no
Sample rate: 16000 Hz
Encoding delay: 1105
Padding: 578
Generating waveform data...
Samples per pixel: 256
Input channels: 2
Output channels: 1
Done: 100%
Frames decoded: 199 (0:07.164)
Generated 444 points
Output file: test.json
Resolution: 8 bits
Channels: 1
Done
```

**Comment by GonzaloGPF** [comment]
When processing a wav file it doesnt shows any `Frames decoded` information.
Is it possible to get the duration of an wav file?
Thanks!

**Comment by chrisn** [comment]
For WAV files, the output is a bit different - you can use the `Frames` (reported from the WAV file header) or `Read x frames` (the number of frames actually read from the file) and then calculate the duration in seconds yourself: 113519 / 16000 = 7.095 seconds.

If it's useful, I could make a simple change to report the duration in seconds, so `Read 113519 frames (00:07.095)`, for example.

```
$ audiowaveform -i test_file_stereo.wav -o test.dat -b 8
Input file: test_file_stereo.wav
Frames: 11351
Sample rate: 16000 Hz
Channels: 2
Format: 0x10002
Sections: 1
Seekable: yes
Generating waveform data...
Samples per pixel: 256
Input channels: 2
Output channels: 1
Done: 100%
Read 113519 frames
Generated 444 points
Output file: test.dat
Resolution: 8 bits
Channels: 1
Done
```

**Comment by PierBover** [comment]
I opted for using the `mediainfo` command to get the duration and other metadata.
