### ISSUE TITLE
Replicating wav2json output

### ISSUE THREAD

**Issue by samueleastdev** [bbc/audiowaveform#136]
Hi All,

I have been using wav2json for a while on my mac https://github.com/beschulz/wav2json

I am building a ElectronJs app and I would like to use audiowaveform, the issue I am having is output.

My output of a converted wav2json file looks like this (truncated it as its really long).
~~~
{
  "_generator":"wav2json version 0.4 on Darwin (http://goo.gl/af7wg)",
  "left": [0.124603,0.270844,0.73053,0.277039,0.301086,0.546631,0.339264,0.474243,
~~~

The same file converted using audiowaveform creates this.
~~~
{"version":2,"channels":1,"sample_rate":48000,"samples_per_pixel":256,"bits":8,"length":961664,"data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-4,5,-5,5,-5,6,-6,
~~~

Is it possible to create a output similar to the wav2json output I am only asking because if it is possible I wont need to re write my javascript that builds the visual waveform for the player so thought it was worth asking here as I might be missing something.

Thanks

**Comment by chrisn** [comment]
I don't have any plans to implement that particular format, sorry. It seems fairly straightforward to transform the audiowaveform output into whatever form you need.

**Comment by samueleastdev** [comment]
Ok no problem, thanks
