### ISSUE TITLE
How to convert json to binary format?

### ISSUE THREAD

**Issue by wong2** [bbc/audiowaveform#137]

**Comment by chrisn** [comment]
audiowaveform doesn't currently accept JSON files as input. It could be added, but it's not been a high priority so far because (in our use), we create and store the binary format, and convert to JSON when needed. I'm happy to consider adding this feature though, if it's useful to you.

**Comment by chrisn** [comment]
See also #18.

**Comment by chrisn** [comment]
I have added JSON support in https://github.com/bbc/audiowaveform/commit/dccc7ade7f20f63f161e4c1ab700605234e843d2.
