### ISSUE TITLE
Misleading error message when using `--pixels-per-second` and `--end`

### ISSUE THREAD

**Issue by deanobarnett** [bbc/audiowaveform#144]
## Problem

When using `audiowaveform` with the `--pixels-per-second` and the `--end` flags, I receive the following error.
```
Specify either end time or zoom level, but not both
```

This is a little misleading as the `--zoom` option is not present.

## Expected

I would expect to see an error message like:
```
Specify either end time or pixels per second, but not both
```

**Comment by chrisn** [comment]
Good suggestion, thank you. I have now clarified the error messages.
