### ISSUE TITLE
How to get duration from peak data?

### ISSUE THREAD

**Issue by patrickAsare** [bbc/audiowaveform#147]
Ho do you calculate the duration from peak json?

e.g. 

{"version":2,"channels":1,"sample_rate":44100,"samples_per_pixel":2205,"bits":8,"length":427,"data":[-0.86,0.99,-0.83,0.81,-0.71,0.65,-0.54,0.63,-0.58,0.58,-0.43,0.49,-0.42,0.54,-0.43,0.51,-0.46,0.46,-0.35,0.39,-0.35,0.4,-0.4,0.39,-0.4,0.32,-0.79,0.69,-0.71,0.61,-0.46,0.38,-0.64,0.56,-0.62,0.64,-0.43,0.38,-0.33,0.4,-0.39,0.4,-0.32,0.36,-0.43,0.39,-0.43,0.5,-0.28,0.39,-0.47,0.35,-0.51,0.42,-0.46,0.43,-0.43,0.33,-0.42,0.39,-0.51,0.46,-0.44,0.47,-0.47,0.44,-0.79,0.64,-0.76,0.61,-0.58,0.47,-0.68,0.53,-0.74,0.63,-0.46,0.44,-0.37,0.42,-0.82,0.74,-0.54,0.53,-0.58,0.57,-0.89,0.78,-0.74,0.67,-0.51,0.5,-0.71,0.68,-0.69,0.76,-0.67,0.58,-0.69,0.53,-0.76,0.74,-0.64,0.6,-0.46,0.47,-0.87,0.96,-0.86,0.9,-0.67,0.58,-0.71,0.57,-0.71,0.81,-0.51,0.57,-0.44,0.5,-0.57,0.68,-0.6,0.71,-0.58,0.49,-0.61,0.57,-0.62,0.58,-0.61,0.57,-0.69,0.58,-0.81,0.61,-0.51,0.5,-0.54,0.43,-0.56,0.47,-0.47,0.44,-0.44,0.5,-0.54,0.47,-0.4,0.47,-0.46,0.51,-0.43,0.44,-0.42,0.39,-0.46,0.36,-0.42,0.43,-0.37,0.39,-0.36,0.39,-0.26,0.33,-0.32,0.31,-0.36,0.36,-0.46,0.32,-0.36,0.43,-0.51,0.5,-0.4,0.5,-0.43,0.58,-0.81,0.76,-0.6,0.6,-0.53,0.44,-0.76,0.81,-0.5,0.5,-0.4,0.4,-0.71,0.56,-0.78,0.68,-0.57,0.63,-0.46,0.43,-0.86,0.64,-0.53,0.46,-0.44,0.44,-0.76,0.61,-0.53,0.63,-0.4,0.43,-0.74,0.85,-0.86,0.9,-0.75,0.65,-0.54,0.61,-0.51,0.6,-0.49,0.47,-0.47,0.38,-0.67,0.44,-0.53,0.46,-0.53,0.6,-0.54,0.53,-0.51,0.42,-0.32,0.31,-0.31,0.28,-0.72,0.58,-0.43,0.44,-0.58,0.44,-0.61,0.61,-0.61,0.58,-0.58,0.5,-0.5,0.53,-0.46,0.47,-0.6,0.56,-0.56,0.46,-0.42,0.53,-0.49,0.43,-0.4,0.39,-0.4,0.42,-0.36,0.4,-0.39,0.46,-0.4,0.43,-0.35,0.43,-0.35,0.38,-0.28,0.36,-0.81,0.78,-0.46,0.51,-0.5,0.4,-0.79,0.68,-0.6,0.6,-0.37,0.32,-0.87,0.81,-0.68,0.76,-0.47,0.47,-0.37,0.38,-0.89,0.86,-0.42,0.51,-0.44,0.44,-0.92,0.76,-0.69,0.58,-0.64,0.68,-0.81,0.81,-0.94,0.6,-0.56,0.57,-0.33,0.39,-0.92,0.94,-0.87,0.92,-0.69,0.67,-0.65,0.69,-0.61,0.63,-0.5,0.57,-0.44,0.47,-0.51,0.49,-0.4,0.4,-0.29,0.44,-0.36,0.35,-0.31,0.51,-0.32,0.35,-0.46,0.43,-0.65,0.53,-0.5,0.51,-0.44,0.44,-0.47,0.51,-0.57,0.57,-0.56,0.57,-0.36,0.35,-0.39,0.42,-0.43,0.56,-0.42,0.43,-0.36,0.39,-0.29,0.31,-0.36,0.24,-0.32,0.36,-0.39,0.35,-0.4,0.32,-0.26,0.28,-0.32,0.32,-0.39,0.36,-0.65,0.64,-0.51,0.47,-0.47,0.49,-0.46,0.51,-0.51,0.53,-0.49,0.42,-0.36,0.35,-0.76,0.75,-0.6,0.67,-0.5,0.43,-0.74,0.76,-0.75,0.74,-0.37,0.4,-0.61,0.76,-0.67,0.67,-0.54,0.5,-0.43,0.43,-0.62,0.61,-0.57,0.57,-0.44,0.43,-0.92,0.97,-0.92,0.93,-0.81,0.71,-0.78,0.54,-0.71,0.61,-0.57,0.49,-0.46,0.5,-0.54,0.61,-0.54,0.61,-0.64,0.56,-0.56,0.56,-0.49,0.63,-0.51,0.56,-0.67,0.65,-0.78,0.54,-0.54,0.58,-0.44,0.47,-0.61,0.61,-0.56,0.56,-0.49,0.61,-0.54,0.58,-0.49,0.56,-0.57,0.53,-0.56,0.51,-0.49,0.51,-0.5,0.44,-0.36,0.5,-0.36,0.63,-0.37,0.65,-0.36,0.56,-0.56,0.58,-0.56,0.6,-0.61,0.53,-0.65,0.71,-0.64,0.68,-0.57,0.64,-0.49,0.56,-0.74,0.72,-0.58,0.76,-0.56,0.67,-0.97,0.94,-0.83,0.74,-0.64,0.61,-0.85,0.85,-0.79,0.78,-0.58,0.54,-0.64,0.5,-0.69,0.81,-0.5,0.64,-0.47,0.49,-0.83,0.74,-0.67,0.61,-0.53,0.54,-0.97,0.82,-0.82,0.93,-0.82,0.78,-0.62,0.54,-0.64,0.53,-0.56,0.49,-0.5,0.63,-0.6,0.49,-0.49,0.6,-0.49,0.51,-0.49,0.39,-0.51,0.33,-0.35,0.43,-0.44,0.42,-0.57,0.61,-0.49,0.54,-0.42,0.36,-0.51,0.49,-0.54,0.57,-0.43,0.58,-0.43,0.57,-0.33,0.54,-0.36,0.4,-0.29,0.26,-0.26,0.39,-0.35,0.38,-0.35,0.4,-0.37,0.38,-0.43,0.33,-0.35,0.39,-0.37,0.36,-0.36,0.38,-0.43,0.43,-0.43,0.36,-0.65,0.68,-0.6,0.57,-0.43,0.46,-0.83,0.61,-0.69,0.69,-0.46,0.44,-1.01,0.99,-1.03,0.97,-0.46,0.44,-0.47,0.44,-0.76,0.88,-0.47,0.51,-0.5,0.51,-1.01,0.85,-0.68,0.76,-0.47,0.53,-0.37,0.5,-0.35,0.42,-0.36,0.38,-0.36,0.36,-0.93,0.94,-0.83,0.74,-0.61,0.61,-0.62,0.63,-0.61,0.57,-0.67,0.43,-0.58,0.42,-0.46,0.6,-0.51,0.47,-0.42,0.51,-0.42,0.47,-0.44,0.53,-0.46,0.39,-0.71,0.61,-0.72,0.6,-0.44,0.44,-0.53,0.47,-0.56,0.6,-0.51,0.47,-0.54,0.54,-0.53,0.57,-0.42,0.44,-0.42,0.44,-0.47,0.54,-0.37,0.43,-0.46,0.42,-0.44,0.49,-0.42,0.46,-0.5,0.38,-0.43,0.46,-0.31,0.36,-0.36,0.4,-0.42,0.38,-0.83,0.82,-0.62,0.69,-0.43,0.44,-0.57,0.53,-0.65,0.5,-0.4,0.38,-0.43,0.42,-0.85,0.82,-0.5,0.53,-0.44,0.46,-0.9,0.79,-0.6,0.58,-0.39,0.44,-0.96,0.85,-0.79,0.78,-0.37,0.47,-0.5,0.54,-0.79,0.65,-0.39,0.46,-0.36,0.35,-0.86,0.93,-0.83,0.83,-0.74,0.71,-0.71,0.58,-0.62,0.58,-0.62,0.6,-0.56,0.47,-0.47,0.51,-0.35,0.38,-0.36,0.5,-0.4,0.39,-0.42,0.46,-0.42,0.46,-0.82,0.78,-0.72,0.58,-0.67,0.47,-0.61,0.6,-0.71,0.65,-0.62,0.5,-0.57,0.56,-0.43,0.54,-0.46,0.4,-0.46,0.43,-0.44,0.47,-0.54,0.46,-0.44,0.47,-0.57,0.43,-0.4,0.5,-0.49,0.46,-0.44,0.42,-0.44,0.51,-0.51,0.38,-0.47,0.49,-0.81,1,-0.81,0.76,-0.53,0.43,-0.39,0.43,-0.93,0.88,-0.46,0.47,-0.26,0.28,-0.81,0.81,-0.54,0.49,-0.44,0.5,-0.82,0.67,-0.75,0.71,-0.5,0.51,-0.4,0.39,-0.72,0.56,-0.53,0.5,-0.56,0.44,-0.82,0.69,-0.67,0.74,-0.44,0.53,-0.39,0.42]}

Thanks!

**Comment by chrisn** [comment]
`duration = length * samples_per_pixel / sample_rate`

**Comment by patrickAsare** [comment]
Thank you @chrisn
