### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by bariscankurtkaya** [bbc/audiowaveform#148]
I installed audiowaveform on my Amazon-Linux server which is based CentOs7-x86_64 and now I am getting this error when I type audiowaveform on console.

`audiowaveform: symbol lookup error: audiowaveform: undefined symbol: _ZN5boost15program_options3argE`

I did all these commands in the below.

`$ sudo yum update`
`$ sudo amazon-linux-extras install epel`
`$ sudo yum localinstall --nogpgcheck \ https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm`
`$ sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
`$ sudo yum install -y --enablerepo=epel libmad-devel`
`$ sudo yum install -y redhat-lsb-core rpm-build wget \ git make cmake gcc-c++ libid3tag-devel libsndfile-devel gd-devel boost-devel`
`$ sudo yum install git make cmake gcc-c++ libmad-devel \ libid3tag-devel libsndfile-devel gd-devel boost-devel`

`$sudo yum localinstall \ https://github.com/bbc/audiowaveform/releases/download/1.5.1/audiowaveform-1.5.1-1.el7.x86_64.rpm`

--------------------------------------------------

I actually tried my other os which are ubuntu and macOs and 1.5.1 version worked so I couldn't understand the problem. I saw some of sites which is on stackoverflow but for different libraries. If you want I can add site links to.

Besides that, I did all of them. 
https://cmake.org/download/ --- https://www.boost.org/users/download/  ----  yum install gcc-c++

**Comment by chrisn** [comment]
Thanks for reporting this, there's clearly a mismatch between audiowaveform and the boost program options dependency, but I'm not sure exactly why. The undefined symbol demangles to `boost::program_options::arg`.

Not related to this problem, but installing shouldn't require all the devel dependencies, this should be enough:

    sudo yum update
    sudo amazon-linux-extras install epel
    sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    sudo yum localinstall https://github.com/bbc/audiowaveform/releases/download/1.5.1/audiowaveform-1.5.1-1.el7.x86_64.rpm

**Comment by chrisn** [comment]
I've just added an Amazon Linux rpm. Please let me know if this works for you.

https://github.com/bbc/audiowaveform/releases/download/1.5.1/audiowaveform-1.5.1-1.amzn2.x86_64.rpm

**Comment by bariscankurtkaya** [comment]
Thank you so much. I will try that way tomorrow, and I will inform you back. @chrisn

**Comment by bariscankurtkaya** [comment]
Thank you so much it works fine right now. 🚀  @chrisn 

<img width="496" alt="Screen Shot 2021-10-04 at 11 01 28" src="https://user-images.githubusercontent.com/33360380/135814964-2e1cc215-02bf-4bb3-bb69-4434b6e1823f.png">
