### ISSUE TITLE
m4a (AAC / ALAC) support?

### ISSUE THREAD

**Issue by richthegeek** [bbc/audiowaveform#15]
I imagine the chances of this are quite remote, as it's a proprietary / patent-encumbered format.

It seems like it's a fairly popular format (for our use-case at least), which is annoying!

**Comment by swordsreversed** [comment]
This would be amazing, re-encoding would be a non-trivial exercise for hundreds of hours of audio. If you can give me a couple of docs as pointers I'll start a pull request on this (NOTE: no C experience whatsoever!)

**Comment by chrisn** [comment]
I agree this would be useful, so I'm having a quick look into it. A couple of options are [libfaad](http://www.audiocoding.com/faad2.html) and [libsox](http://sox.sourceforge.net/). libsox should be straightforward to add, so I'll push a branch for you to test soon.

**Comment by chrisn** [comment]
If someone reading this is a Mac OS X user, can you check that libsox supports m4a audio (I think ffmpeg is needed), and post the homebrew commands needed to install these. Thanks!

**Comment by swordsreversed** [comment]
Ok, spent a little while digging around and i could get sox to convert to m4a, and it is a nightmare. Seemingly no on the internet I could find has this working esp through homebrew. It looks like the current version of sox no longer supports ffmpeg, 

[https://sourceforge.net/p/sox/mailman/message/33267413/](https://sourceforge.net/p/sox/mailman/message/33267413/)

and when I tried 14.4.0 I go errors same as this:

[http://sox.10957.n7.nabble.com/Build-with-ffmpeg-not-working-td2016.html](http://sox.10957.n7.nabble.com/Build-with-ffmpeg-not-working-td2016.html)

So I'm thoroughly stuck at the moment. Is it possible to incorporate ffmpeg directly? I use it on the command line to convert mp3 to m4a currently. Why would we use sox as an intermediate?

**Comment by chrisn** [comment]
Thank you for investigating. The reason for suggesting libsox is that it presents a very simple API for application developers, and internally takes care of all the complexity of parsing file formats and decoding the audio. It supports m4a decoding on Ubuntu via ffmpeg, so it looked to be a simple solution. libfaad on the other hand will be a lot more effort to integrate.

**Comment by swordsreversed** [comment]
Ok sounds, good, i'll have a quick go on setting it up on a docker container. Seems OSX and homebrew aren't compatible with the ffmpeg support/.

**Comment by ffxsam** [comment]
What about libfaac?

**Comment by NicoxDJ** [comment]
After 4 years? What about really support for m4a? I start using Azuracast which is using your JSON wave generator, and i can't use my songs because of it :(

**Comment by chrisn** [comment]
The current workaround is to use ffmpeg to convert m4a to wav, then run through audiowaveform (see the last example [here](https://github.com/bbc/audiowaveform/#examples)). Until we have working m4a support, I suggest raising this with Azuracast.

**Comment by chrisn** [comment]
Closing as not-planned, because I won't be able to distribute binaries due to patent implications.
