### ISSUE TITLE
audiowaveform: error while loading shared libraries: libboost_program_options.so.1.58.0

### ISSUE THREAD

**Issue by Gigamick** [bbc/audiowaveform#150]
Hi, sorry about this but my app relies on Audiowaveform and a few days ago it stopped working.

there error I am getting is

```audiowaveform: error while loading shared libraries: libboost_program_options.so.1.58.0```

and the package I am loading is:

https://launchpad.net/~chris-needham/+archive/ubuntu/ppa/+files/audiowaveform_1.5.1-1xenial1_amd64.deb

Any ideas? I dunno why it just stopped working.

**Comment by chrisn** [comment]
We got this working after discussing via email. Thanks @Gigamick!
