### ISSUE TITLE
Splitting channels not working on .ogg file

### ISSUE THREAD

**Issue by noopc** [bbc/audiowaveform#151]
Version: 1.5.0
Platform: Windows

When generating waveform for an [8-track .ogg file](https://www.brucewiggins.co.uk/Audio/8Channel.ogg), the output contains only one  track/array of data.

Command: `audiowaveform --split-channels --input-format ogg -i my_file.ogg -o my_file.json --pixels-per-second 20 --bits 8`.
Intrestingly, with the --split-channels option, the data field of the output json has more data than without the --split-channels option. Is it possible that the data for different channels is there, but just pushed into a single array?

Extra: When using audiowaveform version 1.5.1, I get the output 
`Failed to read file: {my_filename}.ogg
File contains data in an unimplemented format.`

**Comment by chrisn** [comment]
The data is intended always to be interleaved, so I'm surprised you get that output from MP3. Can you share an example?
