### ISSUE TITLE
Empty image with a huge audio file.

### ISSUE THREAD

**Issue by thunderrous** [bbc/audiowaveform#156]
`audiowaveform --input-filename Record.wav --pixels-per-second 2 --width 85198 --output-filename LastRecord.png`

This is the command i'm using. The file is almost 12 hours long. If i specify smaller width then it can't fit the wave of the entire file.

I got the width by calculating how many seconds there are and mutiplying by two because there's 2 pixels per second.

How do I make it generate the waveform of a huge file in higher resolution so that i can navigate it?

**Comment by chrisn** [comment]
Can you use the `--zoom auto` option to fit the waveform to the desired image width? These commands all work OK for me on a 12 hour file:

```
audiowaveform --input-filename test.ogg --zoom auto --width 50000 --output-filename test1.png
audiowaveform --input-filename test.ogg --zoom auto --width 150000--output-filename test2.png
```

**Comment by thunderrous** [comment]
Doesn't work either.

**Comment by chrisn** [comment]
If you can upload the audio file somewhere, I'll be happy to see if I can reproduce the problem here.

**Comment by thunderrous** [comment]
I'm sorry it's a private thing. I'll close this, I'll just use the audio wave in audacity.
