### ISSUE TITLE
Strange Sample Rate issue with FFMPEg STDIN 

### ISSUE THREAD

**Issue by rkuhnjr** [bbc/audiowaveform#161]
I have to get the JSON peak data on the fly (cant save to a file) from MP4 so I use ffmpeg to pipe into audiowaveform. 
I use windows builds of both products 

When i pipe into audiowave form the sampling rate changes causing the results to not be correct. 

.\ffmpeg.exe -i 5eb858cf-062e-4fcc-94af-6c6159158816.mp4 -f wav - | .\audiowaveform.exe --input-format wav -o rawdata.json

Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf59.17.101
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), **44100 Hz,** stereo, s16, 1411 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.20.100 pcm_s16le
size=    9880kB time=00:00:57.35 bitrate=1411.2kbits/s speed= 261x
video:0kB audio:9880kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000771%
Input file: (stdin)
Frames: 265277391
**Sample rate: 16196 Hz**
Channels: 2
Format: 0x10002
Sections: 1

You notice the sample rate from FFMPEG is 44100 but when read by audiowaveform its reading 16196  
Any idea why? 
If i use ffmpg to create a wav file (with the same command options) AudioWaveForm reads it with the correct sampling rate of 44100 

What can i do to resolve it? I have looked through all switch's on both products and nothing seems to make a difference.

**Comment by chrisn** [comment]
Interesting, I'm not sure. I couldn't reproduce this with one of my own mp4 files. I'm using the ffmpeg build from [here](https://www.gyan.dev/ffmpeg/builds/).

What's the duration of your audio file? If you're able to share a copy of the file, I could try it myself.

**Comment by rkuhnjr** [comment]
Unfortunately its proprietary so I can't share it. I will try the other build at some point but in the meantime i ended up migrating it to an environment that where i can utilize disk I/O to write and read to a file so FFMPeg creates the file and audiowaveform just reads it. That is working flawlessly

**Comment by rkuhnjr** [comment]
It has been driving me nuts so i messed around with it a bit more and found that it is some weird issue with Powershell. Since i am in windows I was using power shell for the command. When i run the identical command with cmd.exe it works perfectly. 

Its obviously an edge case but if anyone else comes across this, dont use powershell...

**Comment by chrisn** [comment]
OK, that is strange. I'm not familiar with PowerShell. The only thing I thought could be happening is that audiowaveform doesn't set the stdin stream to binary mode so could be trying to read the input as text.
