### ISSUE TITLE
Spaces on input filename or path causes no output

### ISSUE THREAD

**Issue by Don1948** [bbc/audiowaveform#162]
Any spaces in the filename or its path will produce no output. Can this be fixed?

**Comment by chrisn** [comment]
Is there any error reported? If the filename has spaces, you can put the file name in quotes. For example, on Windows:

```
audiowaveform -i "test file.mp3" -o "test file.png"
```

**Comment by Don1948** [comment]
Chrisn.

Putting the file name in quotes is the first thing I did and it did not work.
Shell "audiowaveform1 -i "Track -1.mp3" -o Track-1.dat"
Shell "audiowaveform1 -i " & "Track -1.mp3" & " -o Track-1.dat"

But I tried this and it did work:
Shell "audiowaveform1 -i ""Track -1.mp3"" -o Track-1.dat"

Thank you for your help and prompt answer.
________________________________

**Comment by Don1948** [comment]
Chrisn.

Putting the file name in quotes is the first thing I did and it did not work. 
Shell "audiowaveform1 -i "Track -1.mp3" -o Track-1.dat"
Shell "audiowaveform1 -i " & "Track -1.mp3" & " -o Track-1.dat"

But I tried this and it did work:
Shell "audiowaveform1 -i ""Track -1.mp3"" -o Track-1.dat"

Thank you for your help and prompt answer.

**Comment by chrisn** [comment]
It works fine if you type on the command line., so the problem must lie elsewhere. I don't recognise "Shell ..."  so I don't know tool you're using. The only thing I can see from the examples you have nested quotes, so I'd check how these are handled.
