### ISSUE TITLE
Add jpg output format

### ISSUE THREAD

**Issue by Don1948** [bbc/audiowaveform#163]
Can you add industry standard jpg format in addition to png?

**Comment by chrisn** [comment]
I just did some tests, and the output jpeg files are about 10 times the size of PNGs, and with visible compression artefacts. So I'm not sure I want to add jpeg support directly. You can always use something like imagemagick to convert the PNG.

Here's a jpeg example (quality: 90):

![test_file_stereo](https://github.com/bbc/audiowaveform/assets/57790/9aeeda81-4f89-421a-b332-5df29326b532)

Here's the same image as PNG:

![test_file_stereo](https://github.com/bbc/audiowaveform/assets/57790/5eefe4b0-e97a-4fe5-b0fb-704dbcebdc6c)
