### ISSUE TITLE
Different colours for each audio channel

### ISSUE THREAD

**Issue by riban-bw** [bbc/audiowaveform#169]
It would be advantageous to be able to differentiate between audio channel in the waveform display. It may be useful to add a feature to colour channels individually. Maybe it could allow definition of each channel colour as a command line parameter. Maybe this could be a parameter that could be repeated, e.g. to colour left leg red and right leg green:

`audiowaveform -i audio.wav -o waveform.png --waveform-color B00000 --waveform-color 00B000`

It could cycle through the provided colours for each channel, e.g. for a 4 channel wav file the above command would colour the first and third channels red and the second and fourth channels green.

It may be further advantageous to offer an automatic colouring mode that creates a new colour for each channel. This may have the ability to group a configured quantity of channels, e.g. colouring pairs of channels the same colour. Syntax might be something like:

`audiowaveform -i audio.wav -o waveform.png --waveform-color auto --group_channels 2`

**Comment by chrisn** [comment]
Thanks, and sorry for the delay in replying. This is a good suggestion.

I've used a slightly different syntax, so `--waveform-color` now accepts multiple colours, separated by commas:

```
audiowaveform -i audio.wav -o waveform.png --waveform-color B00000,00B000 --split-channels
```

The colours are cycled through, as you suggest, which lets you provide fewer colours than channels.
