### ISSUE TITLE
Compatibility with Centos8/RHEL8

### ISSUE THREAD

**Issue by dnoneill** [bbc/audiowaveform#178]
Right now when I try to install on redhat8 I get the following errors:

```
 - nothing provides libboost_filesystem-mt.so.1.53.0()(64bit) needed by audiowaveform-1.6.0-1.x86_64
  - nothing provides libboost_program_options-mt.so.1.53.0()(64bit) needed by audiowaveform-1.6.0-1.x86_64
  - nothing provides libboost_regex-mt.so.1.53.0()(64bit) needed by audiowaveform-1.6.0-1.x86_64
  - nothing provides libboost_system-mt.so.1.53.0()(64bit) needed by audiowaveform-1.6.0-1.x86_64
  - nothing provides libgd.so.2()(64bit) needed by audiowaveform-1.6.0-1.x86_64
```

For refrence libboost on RHEL 8 is 1.66.
https://rhel.pkgs.org/8/okey-x86_64/boost-filesystem-1.66.0-6.el8.x86_64.rpm.html

**Comment by chrisn** [comment]
What commands did you use to install?

**Comment by chrisn** [comment]
Thanks. Those rpm files are for Centos 7, which I expect won't work on Centos 8. At the time I released 1.6.0, I was unsuccessful in getting it to build on Centos 8 (using the script and Dockerfile in the [rpm](https://github.com/bbc/audiowaveform/tree/master/rpm) folder). I don't recall the detail, but you're welcome to give those a try and see if it now works.

**Comment by chrisn** [comment]
Centos 8 reached [End Of Life](https://www.centos.org/centos-linux-eol/) on December 31, 2021. I found some information [here](https://stackoverflow.com/questions/71066213), to use vault.centos.com. With that [change](https://github.com/bbc/audiowaveform/commit/46cd1b19459e603d8ed5585a3da7747deb51bdad) in place I was able to build, so I have uploaded an rpm to the [Releases](https://github.com/bbc/audiowaveform/releases/) page.

To install, as root:

```
sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
yum install -y epel-release
yum localinstall audiowaveform-1.6.0-1.el8.x86_64.rpm
```

**Comment by dnoneill** [comment]
@chrisn Thank you

**Comment by chrisn** [comment]
I'm happy to help. Please let me know if it works!
