### ISSUE TITLE
Provide a build for Ubuntu Mantic Minotaur?

### ISSUE THREAD

**Issue by YannickGagnon** [bbc/audiowaveform#189]
Hey @chrisn, what would it take to publish a version for Ubuntu Mantic?

Looking at https://github.com/bbc/audiowaveform/tree/master/ubuntu, it looks like it's pretty straight-forward, but is it something you already have a flow for?

**Comment by YannickGagnon** [comment]
We are already using it in production ahahah

**Comment by chrisn** [comment]
The script I use makes it easy to publish for all current Ubuntu versions when I make a new release. Harder is publishing an existing audiowaveform release for a new Ubuntu version, which is currently more of a manual (and fiddly) step, which does need automating.

**Comment by chrisn** [comment]
Thank you. This is a good reminder anyway to improve that packaging script.
