### ISSUE TITLE
Spaces on input filename or path causes error

### ISSUE THREAD

**Issue by def0e0** [bbc/audiowaveform#195]
Any spaces in the filename or its path will produce error. 

![error](https://github.com/bbc/audiowaveform/assets/71279/997107cc-3317-4322-a6ce-d1e790df33fb)

OS: Windows 10 
AudioWaveform: v1.10.0

**Comment by chrisn** [comment]
Thank you for reporting this. I will publish a fix soon.

**Comment by chrisn** [comment]
This is fixed in version 1.10.1. Thanks again!

**Comment by def0e0** [comment]
Wow. So fast. Thank you! :)
