### ISSUE TITLE
Feature request: Gradient colors

### ISSUE THREAD

**Issue by tim-kos** [bbc/audiowaveform#198]
It would be nice to specify and outer color and a center color to display the waveform with a gradient color.

**Comment by chrisn** [comment]
Feel free to contact me directly if this is something you need.

**Comment by chrisn** [comment]
The other option is to generate waveform data files and do the render yourself.

**Comment by tim-kos** [comment]
hey @chrisn 

We'd like you to implement this. Please reach out to first part of my username @transloadit.com via email if you are interested in building this for us. Thanks!
