### ISSUE TITLE
Quiet output option

### ISSUE THREAD

**Issue by kimadactyl** [bbc/audiowaveform#25]
Thanks for the fantastic utility. Would it be possible to have a "quiet" output option? I'm using this in an automated setting and it'd be great to disable the STDOUT output. 

Thanks!

**Comment by chrisn** [comment]
Hi Kim,

Thanks for the feedback. This is related to another feature I've been thinking about: the ability to write the output waveform data/image directly to stdout (as an extension of #13). In this case the information/progress messages would be written to stderr instead, in which case having a `--quiet` option would be useful.

In the meantime you can suppress the output by redirecting stdout:

    audiowaveform -i test.mp3 -o test.dat >/dev/null

Chris

**Comment by kimadactyl** [comment]
Great, thankyou! Will be in touch when my application is a little more polished if that's ok :) the whole peaks.js suite is amazing!
