### ISSUE TITLE
how to install on centos?

### ISSUE THREAD

**Issue by sunilit42** [bbc/audiowaveform#30]
Can you please provide us RPM for that?

**Comment by chrisn** [comment]
We currently only have binaries available for [Ubuntu](https://launchpad.net/~chris-needham/+archive/ubuntu/ppa), but I'd certainly like to see binaries for more OS's. What version of Centos are you targeting, and does audiowaveform build OK from source?

The `CMakeLists.txt` file includes CPack code to generate RPMs, so - for the time being - you should be able to create your own package using `make package`.

**Comment by oncletom** [comment]
I have been able to almost compile `audiowaveform` on CentOS7 but I struggle to install `libmad`.

@sunilit42 do you have any idea how to proceed?

**Comment by sunilit42** [comment]
chrisn :+1: version is EL6

**Comment by oncletom** [comment]
I can give it a go tomorrow, libmad seems to be easier to install on CentOS6 :-)

**Comment by oncletom** [comment]
Hi @sunilit42 – @chrisn and I managed to compile rpm on Centos6 and 7. More on this soon :-)

**Comment by sunilit42** [comment]
hello no need I created json data from by using some other methods. thanks
for your lovely support

**Comment by oncletom** [comment]
Ah good news @sunilit42! How did you do in the end? We could document it if it sounds relevant.

**Comment by sunilit42** [comment]
hello we want json data between 0 to 1. I will share that link with in 2
mins

**Comment by sunilit42** [comment]
we used below link for that:
https://github.com/beschulz/wav2json

By using sox we convert mp3  file into wav then wav to json.

**Comment by chrisn** [comment]
Thanks for the update, Sunil, and the pointer to waveformjs.org. We'll keep this issue open until we publish build instructions for CentOS and possibly make RPMs available.

**Comment by sunilit42** [comment]
is that possible using your script convert data same as https://github.com/beschulz/wav2json between 0 to 1?

**Comment by chrisn** [comment]
audiowaveform is designed to generate data for use with [Peaks.js](https://github.com/bbcrd/peaks.js), and our data formats are documented [here](https://github.com/bbcrd/audiowaveform/blob/master/doc/DataFormat.md). It's possible we could  extended the program to also output waveformjs.org compatible data, or write a separate converter script. We'll give this some thought.

**Comment by infovore** [comment]
Hello - I've installed audiowaveform successfully on both Centos 6.6 and 7.0. 

7.0 was relatively straightforward; I think I just needed EPEL available, and all the dependencies supplied in the OS worked fine.

Centos 6.6 took more work, but I took notes on the process as I went and can regurgitate them here: 

In short, I used EPEL, an rpmforge `libmad-devel` release, used a custom rpm of `boost` as the Centos 6.6 one was out of date (and had no joy compiling it myself) and finally used `devtoolset-3` to supply an up-to-date `g++`. With all that in mind,
this gist is a list of what worked for me and an ops colleague: https://gist.github.com/infovore/6f38f8e76ce2b06df0a8

**Comment by infovore** [comment]
(The single most annoying thing was the out-of-date `boost` inside CentOS).

**Comment by oncletom** [comment]
@infovore have you tried to install the `boost148-devel` package? Therefore `cmake` needs to be given `-D BOOST_LIBRARYDIR=/usr/lib64/boost148 -D BOOST_INCLUDE_DIR=/usr/include/boost148`.

**Comment by infovore** [comment]
@oncletom ah, I did not try that. To be honest, we're entirely satisfied with the solution we've got for our CentOS environment, but duly noted for the future!

**Comment by karthiiivgn** [comment]
hi i am using wav2json json file but our audiowaveform not supported this kind of json data please give the solution. my server has centOS 7 no i am not able to install audiowaveform. please give solution for that.

**Comment by chrisn** [comment]
RPMs for Centos 7 and 8 are now available on the [Releases](https://github.com/bbc/audiowaveform/releases) page. Details for how to build the RPMs are [here](https://github.com/bbc/audiowaveform/tree/master/rpm).
