### ISSUE TITLE
how to zoom the waveform vertically?

### ISSUE THREAD

**Issue by Borys216307** [bbc/audiowaveform#36]
I want to increase the height of the waveform without change the height of image. can you let me know how to do this?

**Comment by chrisn** [comment]
The only way to do this right now is to edit the audio file to adjust the volume before running `audiowaveform`. I could consider adding a new command line option to adjust the amplitude scaling, though. Thanks for the suggestion!

**Comment by chrisn** [comment]
@Borys216307 Please try the `--amplitude-scale` option in the latest release (v1.0.12).
