### ISSUE TITLE
Ubuntu 16.04 LTS package

### ISSUE THREAD

**Issue by tripper54** [bbc/audiowaveform#43]
It would be great if you could add a package for Ubuntu 16.04

**Comment by chrisn** [comment]
I agree, I'll do this soon.

**Comment by sildeag** [comment]
On Ubuntu 16.04 
I linked googlemock/include/gmock and googletest/include/gtest  to audiowaveform/test.  Otherwise the build failed.

I also made the following modifications to CMakeLists.txt in audiowaveform folder.
line 283: `include_directories(${gtest_SOURCE_DIR} ${gmock_SOURCE_DIR} test)`
line 284: `set(TEST_LIBS /home/sildeag/googlemock/mybuild/libgmock_main.a)`
line 286: `target_link_libraries(audiowaveform_tests ${LIBS} ${TEST_LIBS} -lpthread -lm)`
Hoping the line numbers give an indication of which line I am talking about.

How did you handle googlemock and googletest?

**Comment by tripper54** [comment]
This (extract from a Dockerfile) works for me:
````
# audio waveform generator
RUN git clone https://github.com/bbcrd/audiowaveform.git
RUN mkdir /audiowaveform/build
WORKDIR /audiowaveform
RUN wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
RUN tar xzf release-1.8.0.tar.gz
RUN ln -s googletest-release-1.8.0/googletest googletest
RUN ln -s googletest-release-1.8.0/googlemock googlemock
WORKDIR /audiowaveform/build
RUN cmake ..
RUN make
RUN make install
````

**Comment by chrisn** [comment]
@sildeag My development machine is Ubuntu 16.04, and the setup procedure documented in the ReadMe works for me (as reflected in the Dockerfile that @tripper54 has posted). It looks like you're installing googletest into a different directory.

@tripper54 I'm still planning to update the packages on Launchpad, when time allows.

**Comment by sildeag** [comment]
Thanks.

I tried to follow README.md and although I have Docker installed am unfamiliar with it.

I made some changes to CMakeLists.txt for on Ubuntu 16.04 described in issue #50. 
line 89: `$ wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz` 
line 90:`$ tar xzf release-1.8.0.tar.gz` 
line 91:`$ ln -s googletest-release-1.8.0/googletest googletest` 
line 92:`$ ln -s googletest-release-1.8.0/googlemock googlemock` 

In addition I used: 
`(cd audiowaveform/test && ln -s googletest/include/gtest gtest)`
`(cd audiowaveform/test && ln -s googlemock/include/gmock gmock)`

**Comment by chrisn** [comment]
It's not necessary to use Docker. Try these commands in a working directory:

    $ git clone https://github.com/bbc/audiowaveform.git
    $ cd audiowaveform
    $ mkdir build
    $ wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    $ tar xvzf release-1.8.0.tar.gz 
    $ rm release-1.8.0.tar.gz 
    $ ln -s googletest-release-1.8.0/googletest googletest
    $ ln -s googletest-release-1.8.0/googlemock googlemock
    $ cd build
    $ cmake ..
    $ make

**Comment by sildeag** [comment]
Without the further changes I specified above and in issue #50 numerous errors occur on Ubuntu 16.04.  I also am not that familiar with googletest or googlemock so this represented my attempt at a fix without changing too much else.  Everything builds okay for me with these changes.  Sorry.

**Comment by chrisn** [comment]
@sildeag If the documented instructions don't work for you, would you mind raising a new issue and posting the errors you're getting? I'd like this issue to focus on updating the packages in Launchpad. Thanks!

**Comment by sildeag** [comment]
No problem.   I've got it working which was all I needed for the moment - I was intending to use as the basis for an Rcpp11 package tuneRv2.  I can clone again from github, follow the instructions for Ubuntu, and post the errors.  It'll be a couple of days.

**Comment by ekcheng** [comment]
Any updates on adding a package for Ubuntu 16.04?

**Comment by infovore** [comment]
+1 to this; I have Ansible scripts that will happily compile from source, but it's frustrating to be offered packages for older LTS servers and not 16.04... and I'd rather use those.

**Comment by chrisn** [comment]
This is on my to-do list. Will get to it as and when time allows.

**Comment by mchanton** [comment]
Is there any update on this?

**Comment by sildeag** [comment]
The instructions specified on Jan 3, 2017 worked on Ubuntu 18.04 with one change.  `libgd2-xpm-dev` needs to be replaced with `libgd-dev`.

**Comment by mchanton** [comment]
I managed to get it to work with Ubuntu 16.04 LTS. I just had to manually pick the version for lots of dependencies and manually install those packages. Like the packages wanted version "XY" but apt wanted to install "XY-ubuntu2". Manually installing package=XY worked.

**Comment by dbpolito** [comment]
Would love to see this too ❤️

**Comment by sildeag** [comment]
On Ubuntu 18.04 LTS this worked:
$ sudo apt-get install git make cmake gcc g++ libmad0-dev libid3tag0-dev libsndfile1-dev libgd-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev
$ git clone https://github.com/bbc/audiowaveform.git
$ cd audiowaveform
$ wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
$ tar xvzf release-1.8.0.tar.gz 
$ rm release-1.8.0.tar.gz 
$ ln -s googletest-release-1.8.0/googletest googletest
$ ln -s googletest-release-1.8.0/googlemock googlemock
$ mkdir build
$ cd build
$ cmake ..
$ make

**Comment by chrisn** [comment]
I have just uploaded audiowaveform v1.2.2 Ubuntu packages for 14.04 (Trusty), 16.04 (Xenial), 17.10 (Artful), and 18.04 (Bionic) to Launchpad [here](https://launchpad.net/~chris-needham/+archive/ubuntu/ppa).

To install:
```
sudo add-apt-repository ppa:chris-needham/ppa
sudo apt-get update
sudo apt-get install audiowaveform
```
I'll aim to keep this up to date with new releases. Please let me know if you encounter any issues.

**Comment by chrisn** [comment]
I'll close this, please raise a new issue if there are any problems installing.
