### ISSUE TITLE
Unable to make on CentOS 6.8 x86_64

### ISSUE THREAD

**Issue by usefulz** [bbc/audiowaveform#44]
cmake3 version 3.5.2

> [~/audiowaveform/build]# make
> [  2%] Built target doc
> [  4%] Building CXX object CMakeFiles/audiowaveform.dir/src/Main.cpp.o
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:13:
> In file included from /usr/include/boost148/boost/program_options/value_semantic.hpp:14:
> /usr/include/boost148/boost/lexical_cast.hpp:830:60: warning: implicit
>       conversion loses integer precision: 'unsigned long' to 'unsigned int'
>       [-Wshorten-64-to-32]
>             unsigned int last_grouping_pos = grouping_size - 1;
>                          ~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~^~~
> /root/audiowaveform/src/Main.cpp:33:15: error: static_assert expression is not
>       an integral constant expression
> static_assert(std::numeric_limits<int>::max() >= 2147483647L, "size of int");
>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /root/audiowaveform/src/Main.cpp:33:15: note: non-constexpr function 'max'
>       cannot be used in a constant expression
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/limits:778:18: note: 
>       declared here
>       static int max() throw()
>                  ^
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:11:
> In file included from /usr/include/boost148/boost/program_options/config.hpp:10:
> In file included from /usr/include/boost148/boost/config.hpp:40:
> In file included from /usr/include/boost148/boost/config/select_stdlib_config.hpp:37:
> In file included from /usr/include/boost148/boost/config/no_tr1/utility.hpp:21:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/utility:63:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:60:
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:57:14: error: 
>       rvalue reference to type 'typename std::remove_reference<placeholder
>       *&>::type' (aka 'boost::any::placeholder *') cannot bind to lvalue of type
>       'boost::any::placeholder *'
>     { return __t; }
>              ^~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:81:19: note: 
>       in instantiation of function template specialization
>       'std::move<boost::any::placeholder *&>' requested here
>       _Tp __tmp = _GLIBCXX_MOVE(__a);
>                   ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:61:33: note: 
>       expanded from macro '_GLIBCXX_MOVE'
> #define _GLIBCXX_MOVE(_Tp) std::move(_Tp)
>                                 ^
> /usr/include/boost148/boost/any.hpp:64:18: note: in instantiation of function
>       template specialization 'std::swap<boost::any::placeholder *>' requested
>       here
>             std::swap(content, rhs.content);
>                  ^
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:11:
> In file included from /usr/include/boost148/boost/program_options/config.hpp:10:
> In file included from /usr/include/boost148/boost/config.hpp:40:
> In file included from /usr/include/boost148/boost/config/select_stdlib_config.hpp:37:
> In file included from /usr/include/boost148/boost/config/no_tr1/utility.hpp:21:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/utility:63:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:60:
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:57:14: error: 
>       rvalue reference to type 'vector<[2 * ...]>' cannot bind to lvalue of type
>       'vector<[2 * ...]>'
>     { return __t; }
>              ^~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_stack.h:135:16: note: 
>       in instantiation of function template specialization
>       'std::move<std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> > &>' requested
>       here
>       : c(std::move(__c)) { }
>                ^
> /usr/include/boost148/boost/filesystem/v3/operations.hpp:674:7: note: in
>       instantiation of member function
>       'std::stack<boost::filesystem3::directory_iterator,
>       std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> > >::stack'
>       requested here
>       recur_dir_itr_imp() : m_level(0), m_options(symlink_option::none) {}
>       ^
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:12:
> In file included from /usr/include/boost148/boost/program_options/errors.hpp:14:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/vector:65:
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:258:15: error: 
>       no matching function for call to 'forward'
>       : _Base(std::forward<_Base>(__x)) { }
>               ^~~~~~~~~~~~~~~~~~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_stack.h:135:9: note: 
>       in instantiation of member function
>       'std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> >::vector'
>       requested here
>       : c(std::move(__c)) { }
>         ^
> /usr/include/boost148/boost/filesystem/v3/operations.hpp:674:7: note: in
>       instantiation of member function
>       'std::stack<boost::filesystem3::directory_iterator,
>       std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> > >::stack'
>       requested here
>       recur_dir_itr_imp() : m_level(0), m_options(symlink_option::none) {}
>       ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:51:5: note: 
>       candidate function [with _Tp =
>       std::_Vector_base<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> >] not viable: no
>       known conversion from 'std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> >' to 'typename
>       std::identity<_Vector_base<directory_iterator,
>       allocator<directory_iterator> > >::type &&' (aka
>       'std::_Vector_base<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> > &&') for 1st
>       argument
>     forward(typename std::identity<_Tp>::type&& __t)
>     ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:57:14: error: 
>       rvalue reference to type 'typename
>       std::remove_reference<directory_iterator &>::type' (aka
>       'boost::filesystem3::directory_iterator') cannot bind to lvalue of type
>       'boost::filesystem3::directory_iterator'
>     { return __t; }
>              ^~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_stack.h:188:26: note: 
>       in instantiation of function template specialization
>       'std::move<boost::filesystem3::directory_iterator &>' requested here
>       { c.push_back(std::move(__x)); }
>                          ^
> /usr/include/boost148/boost/filesystem/v3/operations.hpp:697:19: note: in
>       instantiation of member function
>       'std::stack<boost::filesystem3::directory_iterator,
>       std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> > >::push'
>       requested here
>           m_stack.push(directory_iterator(m_stack.top()->path()));
>                   ^
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:12:
> In file included from /usr/include/boost148/boost/program_options/errors.hpp:14:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/vector:65:
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:747:22: error: 
>       no matching function for call to 'move'
>       { emplace_back(std::move(__x)); }
>                      ^~~~~~~~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_stack.h:188:11: note: 
>       in instantiation of member function
>       'std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> >::push_back'
>       requested here
>       { c.push_back(std::move(__x)); }
>           ^
> /usr/include/boost148/boost/filesystem/v3/operations.hpp:697:19: note: in
>       instantiation of member function
>       'std::stack<boost::filesystem3::directory_iterator,
>       std::vector<boost::filesystem3::directory_iterator,
>       std::allocator<boost::filesystem3::directory_iterator> > >::push'
>       requested here
>           m_stack.push(directory_iterator(m_stack.top()->path()));
>                   ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:56:5: note: 
>       candidate template ignored: substitution failure [with _Tp =
>       boost::filesystem3::directory_iterator &]
>     move(_Tp&& __t)
>     ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algobase.h:491:5: note: 
>       candidate function template not viable: requires 3 arguments, but 1 was
>       provided
>     move(_II __first, _II __last, _OI __result)
>     ^
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:11:
> In file included from /usr/include/boost148/boost/program_options/config.hpp:10:
> In file included from /usr/include/boost148/boost/config.hpp:40:
> In file included from /usr/include/boost148/boost/config/select_stdlib_config.hpp:37:
> In file included from /usr/include/boost148/boost/config/no_tr1/utility.hpp:21:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/utility:63:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:60:
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:57:14: error: 
>       rvalue reference to type 'typename std::remove_reference<recur_dir_itr_imp
>       *&>::type' (aka 'boost::filesystem3::detail::recur_dir_itr_imp *') cannot
>       bind to lvalue of type 'boost::filesystem3::detail::recur_dir_itr_imp *'
>     { return __t; }
>              ^~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:81:19: note: 
>       in instantiation of function template specialization
>       'std::move<boost::filesystem3::detail::recur_dir_itr_imp *&>' requested
>       here
>       _Tp __tmp = _GLIBCXX_MOVE(__a);
>                   ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:61:33: note: 
>       expanded from macro '_GLIBCXX_MOVE'
> #define _GLIBCXX_MOVE(_Tp) std::move(_Tp)
>                                 ^
> /usr/include/boost148/boost/smart_ptr/shared_ptr.hpp:448:14: note: in
>       instantiation of function template specialization
>       'std::swap<boost::filesystem3::detail::recur_dir_itr_imp *>' requested
>       here
>         std::swap(px, other.px);
>              ^
> /usr/include/boost148/boost/smart_ptr/shared_ptr.hpp:392:21: note: in
>       instantiation of member function
>       'boost::shared_ptr<boost::filesystem3::detail::recur_dir_itr_imp>::swap'
>       requested here
>         this_type().swap(*this);
>                     ^
> /usr/include/boost148/boost/filesystem/v3/operations.hpp:756:17: note: in
>       instantiation of member function
>       'boost::shared_ptr<boost::filesystem3::detail::recur_dir_itr_imp>::reset'
>       requested here
>         { m_imp.reset (); }
>                 ^
> In file included from /root/audiowaveform/src/Main.cpp:25:
> In file included from /root/audiowaveform/src/Options.h:31:
> In file included from /usr/include/boost148/boost/program_options.hpp:15:
> In file included from /usr/include/boost148/boost/program_options/options_description.hpp:11:
> In file included from /usr/include/boost148/boost/program_options/config.hpp:10:
> In file included from /usr/include/boost148/boost/config.hpp:40:
> In file included from /usr/include/boost148/boost/config/select_stdlib_config.hpp:37:
> In file included from /usr/include/boost148/boost/config/no_tr1/utility.hpp:21:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/utility:63:
> In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:60:
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:57:14: error: 
>       rvalue reference to type 'typename std::remove_reference<m_imp *&>::type'
>       (aka 'boost::filesystem3::filesystem_error::m_imp *') cannot bind to
>       lvalue of type 'boost::filesystem3::filesystem_error::m_imp *'
>     { return __t; }
>              ^~~
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:81:19: note: 
>       in instantiation of function template specialization
>       'std::move<boost::filesystem3::filesystem_error::m_imp *&>' requested here
>       _Tp __tmp = _GLIBCXX_MOVE(__a);
>                   ^
> /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:61:33: note: 
>       expanded from macro '_GLIBCXX_MOVE'
> #define _GLIBCXX_MOVE(_Tp) std::move(_Tp)
>                                 ^
> /usr/include/boost148/boost/smart_ptr/shared_ptr.hpp:448:14: note: in
>       instantiation of function template specialization
>       'std::swap<boost::filesystem3::filesystem_error::m_imp *>' requested here
>         std::swap(px, other.px);
>              ^
> /usr/include/boost148/boost/smart_ptr/shared_ptr.hpp:398:22: note: in
>       instantiation of member function
>       'boost::shared_ptr<boost::filesystem3::filesystem_error::m_imp>::swap'
>       requested here
>         this_type(p).swap(*this);
>                      ^
> /usr/include/boost148/boost/filesystem/v3/operations.hpp:897:19: note: in
>       instantiation of function template specialization
>       'boost::shared_ptr<boost::filesystem3::filesystem_error::m_imp>::reset<boost::filesystem3::filesystem_error::m_imp>'
>       requested here
>         m_imp_ptr.reset(new m_imp);
>                   ^
> 1 warning and 8 errors generated.
> make[2]: *** [CMakeFiles/audiowaveform.dir/src/Main.cpp.o] Error 1
> make[1]: *** [CMakeFiles/audiowaveform.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by chrisn** [comment]
audiowaveform requires g++ 4.6.3 or later and it looks like you're using 4.4.7.  The `CMakeLists.txt` file includes a version check, so running `cmake ..` should have report an error.

**Comment by usefulz** [comment]
I was able to get it compiled by slightly modifying https://gist.github.com/infovore/6f38f8e76ce2b06df0a8
