### ISSUE TITLE
Is it helpful to cut auto ringtones from MP3 (where vocals start)

### ISSUE THREAD

**Issue by Ketizsingh** [bbc/audiowaveform#56]
I need to cut ringtone from MP3 .
Where beat is high or tell timing from  vocal starts and ended.

**Comment by chrisn** [comment]
Hi, thanks for your interest in this project. audiowaveform doesn't analyse the audio, so it can't distinguish ringtones or vocals, etc. Maybe you could ask [here](https://dsp.stackexchange.com/)?
