### ISSUE TITLE
How to statically link libsndfile.so.1?

### ISSUE THREAD

**Issue by ffxsam** [bbc/audiowaveform#57]
How do I modify the configure and make scripts so that `libsndfile.so.1` is embedded in the binary? I need a single, working binary file with no external dependencies.

Thanks!

**Comment by chrisn** [comment]
I would like to enable a full static link (see [here](https://github.com/bbc/audiowaveform/issues/35#issuecomment-215664632) for details). There are a lot more dependencies than just libsndfile, though.

**Comment by ffxsam** [comment]
Awesome, thanks for the link! This is exactly why I need to do so (running this on Lambda).

**Comment by ffxsam** [comment]
Though it looks like no one ever came up with a working solution..

**Comment by chrisn** [comment]
Hi Sam, Sadly not, but I would really like to solve it.

**Comment by ffxsam** [comment]
I'm sure with enough people working on it, we'll figure it out! (then we can document it and add that to the repo)

**Comment by MileanCo** [comment]
I'm also interested in a static executable for this!
My intent is to run this on a AWS Lambda function

**Comment by amrfaisal** [comment]
+1 We need a way to deploy this on lambda.
