### ISSUE TITLE
how to calculate the zoom  from audio duration

### ISSUE THREAD

**Issue by medozeus** [bbc/audiowaveform#63]
need to show the waveform from the zero to the end of the audio duration how can i calculate the zoom i notice it depend on width `-w` too and the `-z` lets suppose i have song with 138 second how can i show the waveform from `0` to `138` second with width `-w 480`

**Comment by medozeus** [comment]
i found the `--end` option but i still need to add the duration for the end option need some thing automatically do that

**Comment by chrisn** [comment]
Please see #58.
