### ISSUE TITLE
Get time and Miliseconds 

### ISSUE THREAD

**Issue by MasterCna** [bbc/audiowaveform#71]
Hello,
I want to see all small peaces of time to find Climax in the audio file. For Example: Show the exact time (seconds and miliseconds of audio file) which has large sample (the high volume part). How can I do that?

**Comment by chrisn** [comment]
Hi! Have you tried setting the `-z` option to a low value (2 or 4, maybe)? Could you possibly post an image of the kind of output you'd expect to see?
