### ISSUE TITLE
is it possible to split two channel (stereo) ?

### ISSUE THREAD

**Issue by karthiiivgn** [bbc/audiowaveform#73]
hi 
i'm using audiowaveform its good for getting audio wavform.

i have stereo audio to be displayed in two waveform graph (left-right channels). is it possible?

example link: https://wavesurfer-js.org/examples/
see the Split channels

**Comment by chrisn** [comment]
This isn't currently supported, but I'm open to adding this as a new feature.

To do this, we'll need to define a new version of the [dat and JSON formats](https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md) to support multiple channels. This should be a straightforward extension of the existing formats, with the version field incremented to 2, add a channel count field to the header, and then store the waveform data interleaved like this:

        min value, index 0, channel 0
        max value, index 0, channel 0
        min value, index 0, channel 1
        max value, index 0, channel 1
        min value, index 1, channel 0
        max value, index 1, channel 0
        min value, index 1, channel 1
        max value, index 1, channel 1

etc.

This would mean that libraries that consume this data would need to be updated ([waveform-data.js](https://github.com/bbc/waveform-data.js) and [Peaks.js](https://github.com/bbc/peaks.js/issues/194) primarily).

**Comment by karthiiivgn** [comment]
Thanks for your quick response...
I am looking foreword for your feature

**Comment by karthiiivgn** [comment]
I'm proud of your efficient work. Thanks for giving solution 
when i got the two channel, i am expect two wave graph lines.

**Comment by crx-gus** [comment]
Hey Chris - seconded. We would love to be able to generate a two channel waveform!

**Comment by Vijayalaxmim** [comment]
Hey Chris, is this feature supported ,because I do not see anything in docs .My request is to view 2 channel waveforms separately instead of one in stereotype audio.

**Comment by chrisn** [comment]
Hi @Vijayalaxmim. This feature is not currently supported, I plan to come back to it after the next couple of weeks.

**Comment by chrisn** [comment]
Here's my current thinking on how this feature will work:

* There will be a new `--split-channels` command line option, to enable multiple channel output files.
* For backwards compatibility, if you don't specify `--split-channels`, the output will be the same as it is now, with all input channels merged into a single waveform. Files will continue to use the existing version 1 format.
* When generating waveform data (binary or JSON format), if you specify `--split-channels`, and if the input has more than one channel, the output file will be the new version 2, as described [above](https://github.com/bbc/audiowaveform/issues/73#issuecomment-410223176), and will contain a waveform per channel. For compatibility purposes, if the input has only one channel, the output file will continue to use the version 1 format.
* When generating PNG files, if you specify `--split-channels`, the output image will show all channels from the input file, one above the other, similar to the [example mentioned above](https://github.com/bbc/audiowaveform/issues/73#issue-346894374).
* At a later date, I may consider adding a `--channel` option that allows you to select a single channel for the output waveform data or image file from an input file with multiple channels.

**Comment by chrisn** [comment]
The `--split-chanels` option is in release 1.3.0.

**Comment by crx-gus** [comment]
Awesome work! Thanks.

*Gus Sharples, *
Senior Solutions Architect
*CR-X Pty Ltd*
BIG DATA INTEGRATION

email: gus.sharples@cr-x.com
phone: +61 3 9828 <//+61 3 9828> 9153
mobile: +61 415 313 <//+61 415 313> 228


On 22 November 2018 at 8:15:34 pm, Chris Needham (notifications@github.com)
wrote:

The --split-chanels option is in release 1.3.0.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bbc/audiowaveform/issues/73#issuecomment-440963128>,
or mute
the thread

**Comment by karthiiivgn** [comment]
Great!,

I'm using older version 1.2.0 how to upgrade this

**Comment by chrisn** [comment]
I suggest holding off testing 1.3 for now, I'm not happy with the new v2 header format. I'll publish a version 1.3.2 shortly to fix it.

**Comment by chrisn** [comment]
Version 1.3.2 is now available.

@karthiiivgn On Ubuntu, you can install from my PPA, or on a Mac you can install via Homebrew. Anything else would require building from source. Details are in the README. Please let me know if this feature works for you, feedback welcome.

**Comment by karthiparthi** [comment]
> hi i'm using audiowaveform its good for getting audio wavform.
> 
> i have stereo audio to be displayed in two waveform graph (left-right channels). is it possible?
> 
> example link: https://wavesurfer-js.org/examples/ see the Split channels

This will work

**Comment by sockite** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
