### ISSUE TITLE
Running command using dynamic input/output filenames on a group of folders

### ISSUE THREAD

**Issue by matt3224** [bbc/audiowaveform#74]
Hi,

I need to be able to run the audiowaveform command across a bunch of mp3's in multiple folders. My structure is like this:

```
|- Track1
   |- Mix1.mp3
   |- Mix2.mp3
   |- Mix3.mp3
|- Track2
   |- Mix1.mp3
   |- Mix2.mp3
|- Track3
   |- Mix1.mp3
   |- Mix2.mp3
   |- Mix3.mp3
   |- Mix4.mp3
```

Something like:
`audiowaveform -i **/*.mp3 --pixels-per-second 10 -b 8 -o {filename}.json`

Is there a way i can do this, i essentially need to create waveforms for 2000 mp3's

Any help much appreciated!

**Comment by chrisn** [comment]
Hi Matt. My suggestion would be to write a shell script or maybe a Makefile to automate this.

**Comment by chrisn** [comment]
Here's an example Makefile that will do the job. Note that the output files will be placed in the same directories as the MP3 files, so this will need changing if you want them to go somewhere else.

```Makefile
.SUFFIXES: .mp3 .json

.mp3.json:
	@echo "$< -> $@"
	@audiowaveform -i $< --pixels-per-second 10 -b 8 -o $@ > /dev/null

MP3_FILES = $(shell find . -name "*.mp3")
JSON_FILES = $(patsubst %.mp3, %.json, $(MP3_FILES))

all: $(JSON_FILES)
```

**Comment by matt3224** [comment]
@chrisn I finally implemented this, thank you so much for putting this script together for me, much appreciated!
