### ISSUE TITLE
Intall with Homebrew is not supported

### ISSUE THREAD

**Issue by jackdon** [bbc/audiowaveform#78]
```shell
sudo brew install boost --with-c++11
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by oncletom** [comment]
@jackdon what makes you think the install is not supported?

From what I understand, `brew` warns you about using `sudo` as you install a package (which is weird, I don't have to use `sudo` to install packages on my machine. Have you tried `brew doctor` to debunk the problem?).

**Comment by qodesmith** [comment]
<img width="769" alt="screen shot 2018-11-16 at 10 15 41 pm" src="https://user-images.githubusercontent.com/11034792/48655998-36c1ed80-e9ed-11e8-9d24-33ff74395332.png">

**Comment by chrisn** [comment]
@qodesmith Did you also do `brew tap bbc/audiowaveform`?

**Comment by qodesmith** [comment]
@chrisn That worked! 💯

**Comment by chrisn** [comment]
Good news, thanks!
