### ISSUE TITLE
Couldn't create output file 

### ISSUE THREAD

**Issue by dummyrule** [bbc/audiowaveform#81]
audiowaveform -i three.wav -o test.dat
Input file: three.wav
Frames: 2400768
Sample rate: 8000 Hz
Channels: 3
Format: 0x130002
Sections: 1
Seekable: yes
Can only generate waveform data from mono or stereo input files

I used 3 channel wave file but got the error "Can only generate waveform data from mono or stereo input files "

**Comment by chrisn** [comment]
Please take a look at the latest release, v1.3.3.
