### ISSUE TITLE
CAN'T generate png/dat from mp3 correctly on Ubuntu 16.04

### ISSUE THREAD

**Issue by Rain-g0d** [bbc/audiowaveform#87]
The error example like this:
![image](https://user-images.githubusercontent.com/49190656/55393206-683bef80-556f-11e9-8c89-e8d57a0678ba.png)

i'm pretty sure that my mp3 file is ok.

Help plz!!

**Comment by chrisn** [comment]
This output suggests something wrong with the MP3 file. Can you send me a copy to take a look at? My email address is [here](https://github.com/bbc/audiowaveform/blob/master/ChangeLog#L1).

**Comment by Rain-g0d** [comment]
I have sent the MP3 file to u.Please check.

**Comment by Rain-g0d** [comment]
In fact,my file is in opus format.So thanks a lot for solving my problem!

**Comment by chrisn** [comment]
This issue shows the need for better input validation, added in https://github.com/bbc/audiowaveform/commit/9bc12959375a02c959b98a0cee4c4e618fddd707.
