### ISSUE TITLE
Feature Request: Send waveform results to STDOUT

### ISSUE THREAD

**Issue by joneslee85** [bbc/audiowaveform#88]
Is it possible to produce results to STDOUT instead of file (via `-o` option)? Because I have application with automated pipeline with post-processing pipeline and passing waveform STDOUT to other process is more UNIX-idiom and easier to manage than through an output file.

**Comment by chrisn** [comment]
This is closely related to #13.

**Comment by joneslee85** [comment]
@chrisn I could provide a PR if you want an implementation

**Comment by chrisn** [comment]
I have a branch locally with some work in progress on this. Let me push that, and we can continue from there.

**Comment by chrisn** [comment]
Please take a look at the `stdio2` branch and https://github.com/bbc/audiowaveform/pull/89. Feedback welcome!

**Comment by chrisn** [comment]
This is implemented in the v1.4.0 release.
