### ISSUE TITLE
Tell CMake where to find the compiler

### ISSUE THREAD

**Issue by GioMBG** [bbc/audiowaveform#90]
Hi Staff,
Fedora 29 issue

CMake Error at CMakeLists.txt:31 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

any suggestion ?
always thanks
GioMBG

**Comment by chrisn** [comment]
You can do it like this:

    $ cmake -D CMAKE_C_COMPILER=/path/to/clang -D CMAKE_CXX_COMPILER=/path/to/clang++ ..

**Comment by GioMBG** [comment]
Hi chrisn,

[root@localhost build]# cmake -D CMAKE_C_COMPILER=/path/to/clang -D CMAKE_CXX_COMPILER=/path/to/clang++ ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    /path/to/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

    /path/to/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/root/installers/audiowaveform/googletest-release-1.8.0/build/CMakeFiles/CMakeOutput.log".
See also "/root/installers/audiowaveform/googletest-release-1.8.0/build/CMakeFiles/CMakeError.log".

thanks

**Comment by chrisn** [comment]
The `/path/to/clang` is just an example, you would need to replace this with the actual path to the compiler on your system. Looking at [this page](https://fedora.pkgs.org/29/fedora-x86_64/clang-7.0.0-2.fc29.x86_64.rpm.html), clang should be installed to `/usr/bin/clang` and `/usr/bin/clang++`.

**Comment by chrisn** [comment]
I'll close this, but please re-open if you're still having difficulties. Thanks.
