### ISSUE TITLE
File generating different significantly less values in PHP compared to terminal

### ISSUE THREAD

**Issue by gitbeat** [bbc/audiowaveform#92]
When I use the following command in **Terminal** on **OS X**, I get an output of 1801 generated values (which is the expected amount):
`audiowaveform -i file.mp3 -o wave.json --end {$DURATION} -w 1800`

However when I use **PHP** (`exec` function), it will only ever output 801 values (suspiciously, exactly 1000 points less). The only difference being that I use the exact path of the command `/usr/bin/...` instead of the former.

**Comment by chrisn** [comment]
Is the `-w` option being set in your PHP code? 800 is the default width, if the `-w` option is not supplied.

**Comment by gitbeat** [comment]
Wow, quick reply!
Appears to be, yes:
[PHP Code](https://imgur.com/a/BPC3ygs)

**Comment by gitbeat** [comment]
Found our problem. Turns out `$duration` was being returned as a string and `--end` doesn't like dealing with anything that isn't a float or an integer. So I had to force type by using `(float)$duration`.
