### ISSUE TITLE
Document ability to generate json direct from sound file 

### ISSUE THREAD

**Issue by rivimey** [bbc/audiowaveform#93]
It would be good to document that if a json file is desired, it is possible to output it directly rather than via a .dat intermediate.

This seems to have been left out of the manual, help text, docs etc but at least for 1.3.3 (and I think much earlier) it works fine, according to my testing. I mention this because the wavesurfer.js module has instructions indicating the need to do
```
audiowaveform -i file.mp3 -o file.dat
audiowaveform -i file.dat -o file.json
```

**Comment by chrisn** [comment]
Thanks for your feedback! audiowaveform has had this feature from the very beginning. It is documented in the manpage:

https://github.com/bbc/audiowaveform/blob/6560e270adbb69574b48f244c2e20e9c3694a6b9/doc/audiowaveform.1#L18

and

https://github.com/bbc/audiowaveform/blob/6560e270adbb69574b48f244c2e20e9c3694a6b9/doc/audiowaveform.1#L62

and the same text is in the README. What's missing is an entry in the Examples section, so I can see why people might miss this feature. I'll add an example.

I suggest raising an issue with wavesurfer.js.

**Comment by chrisn** [comment]
Resolved via https://github.com/bbc/audiowaveform/commit/4016a7d77f42c39801de3eb850618ba504cae6ee.

**Comment by rivimey** [comment]
Thank you! :-)
