### ISSUE TITLE
Feature: abillity to output json as floating point in range -1..1

### ISSUE THREAD

**Issue by rivimey** [bbc/audiowaveform#94]
The [wavesurfer](https://wavesurfer-js.org/).js module wants 'peaks' files in json format with data rendered as floats in range -1..0..1 (preferably fairly exactly). The recommended python is:

```
max_val = float(max(data))
new_data = []
for x in data:
    new_data.append(x/max_val)
```
although my preferred version takes account of min(data) too:

```
max_val = float(max(data))
min_val = float(min(data))
scale=max(abs(max_val),abs(min_val))
new_data = []
for x in data:
    new_data.append(x/scale)
```

Is this something that could be done directly in audiowaveform's json output?

**Comment by chrisn** [comment]
I have no plan to add a floating point output format, as it increases the file size for no benefit, and we'd have to add an equivalent binary (.dat) format, which is unnecessary, and if you're rendering an image from the data you'd have to multiply the values anyway.

On the other hand, scaling the waveform is something we already have with the `--amplitude-scale` option, but this only applies to PNG output, not the waveform data outputs, so adding this seams reasonable.

**Comment by rivimey** [comment]
Fair enough about float... and having known max /min int values would indeed help in converting the integer stream to floats.

**Comment by chrisn** [comment]
You're right. The number ranges are mentioned in the [file format documentation](https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md).

**Comment by rivimey** [comment]
Just a thought: perhaps the only change needed is to store the actual min/max of this stream in the output file, from which readers can trivially scale as desired.

**Comment by chrisn** [comment]
Do you mean the absolute min/max possible values (i.e., -128/+127), or the measured values `min(data)` and `max(data)`? The former can be inferred from the `bits` field in the JSON.

BTW, I agree that a -1/+1 representation would be a lot easier to deal with. Part of my reluctance to add it is that I want to guide people using Peaks.js towards using efficient representations. (I think the default 16 bit output format was a mistake, as this level of resolution isn't usually needed for rendering images, and indeed isn't supported in Peaks.js.) So I'm coming round to the idea, the more I think about it :-)

**Comment by rivimey** [comment]
To confirm, I meant measured values not possible values.
