### ISSUE TITLE
Packaging for Debian Buster

### ISSUE THREAD

**Issue by tinyhammers** [bbc/audiowaveform#95]
I've not been able to install this on Debian Buster, as I can add the PPA as there is no release file.
Any plans to fix that, for this awesome thing you're giving us for free 😉

**Comment by greedybro** [comment]
Hi !
Process for build is very well documented in the readme.md, you just have to build on a buster host 😉

**Comment by chrisn** [comment]
Thanks @greedybro. I guess We could provide .deb files as part of the audiowaveform release process. If anyone is interested in contributing a solution and documentation for that, please let us know.

**Comment by aeschylus** [comment]
I'm not that familiar with packaging for linux distros, but there seems to be this folder in master https://github.com/bbc/audiowaveform/tree/master/debian; what else would be necessary to distribute to buster?

The main use case I have is including this as a dependency in a node application, but the docker images I'm using are all buster or alpine. Right now I'm looking at building from source, which might be okay if I use a multi-stage build, but it's an extra hurdle for many.

As a somewhat off-topic aside, this would make a great nodeJS native extension if anyone were keen on that. Then you could simply `npm install` the entire library and use it without shelling out. Though from what I understand there might be quite a lot of header file reorganisation to make that really work well.

**Comment by thespicer21** [comment]
> Hi !
> Process for build is very well documented in the readme.md, you just have to build on a buster host 😉

I can confirm that the build fails on a buster host. Has anybody managed to get it installed on Buster yet?

**Comment by simon1tan1** [comment]
This is pulled from the README file:
### Ubuntu

Binary packages are available on Ubuntu Launchpad [here](https://launchpad.net/~chris-needham/+archive/ubuntu/ppa).

sudo add-apt-repository ppa:chris-needham/ppa
sudo apt-get update
sudo apt-get install audiowaveform

**Comment by chrisn** [comment]
There are now Debian packages available, see the [ReadMe](https://github.com/bbc/audiowaveform#debian) for details.

**Comment by kilgarenone** [comment]
I run into this error `dpkg: error: cannot access archive 'audiowaveform-1.8.1-1-12.amd64.deb': No such file or directory`.

**Comment by sockite** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chrisn** [comment]
What command did you run? Have you downloaded the .deb file from the [Releases page](https://github.com/bbc/audiowaveform/releases/)?

**Comment by kilgarenone** [comment]
i just found this thread https://github.com/bbc/audiowaveform/issues/191 its all good now. sorry for the noise 🙏
