### ISSUE TITLE
Render windowed waveform as video/animation

### ISSUE THREAD

**Issue by faroit** [bbc/audiowaveform#96]
This tool is great for static waveform images. It would be great, though, if it could be extended to generate animation by creating a series of images where the waveform is windows and would scroll across the time as it is being often done in many visualizers.

https://www.youtube.com/watch?v=v8LC8NToEYY

I guess this could be done in post-processing step using video editors, but I think it would make sense to include such a feature here.

**Comment by chrisn** [comment]
Hi @faroit, adding this feature is not something we currently have planned, and I think it may well be better implemented as a separate tool. Have you tried New York Public Radio's [Audiogram](https://github.com/nypublicradio/audiogram) project? I wonder if this could be a closer starting point for what you need.

**Comment by faroit** [comment]
thanks, thats a great pointer!
