### ISSUE TITLE
no PNG output when specifying colors

### ISSUE THREAD

**Issue by alt-bazza** [bbc/audiowaveform#99]
Hi there,

Changing the waveform colours seems to be problematic. The documentation doesn't really specify exactly how you are supposed to supply the arguments so maybe I'm doing it wrong, but after much trial and error I finally got audiowaveform to stop throwing `Invalid color value` errors by using this : 

`--background-color #000000[0]`

Which in turn throws up a new error about '--color' for which there is no mention of in the documentation at all : 

`Error: the required argument for option '--color' is missing`

If I supply any value to --color... 

`--background-color #000000[0] --color #FFFFFF`

... I don't get any more errors but no file is created.

Is this a bug or am I just supplying the wrong arguments here?

**Comment by alt-bazza** [comment]
Cracked it, for anybody else having issues with this the colours have to be supplied as follows :

`--background-color 00000000 --waveform-color 464646FF --border-color 00000000`

Would help others if the documentation was updated to show an example specifying some colour changes.

**Comment by chrisn** [comment]
Yes, some command shells will interpret the `#` character as the start of a comment.
